abbreviations = {
    'P200': 'Engine Ld',
    'P201': 'Inject Dty',
    'P202': 'Boost rel',
    'E1': 'IAM multi',
    'E5': 'Boost Err',
    'E11': 'Knock corr',
    'E12': 'Fine Knock',
    'E20': 'Boost abs',
    'E25': 'Gear',
    'P1': 'Eng Ld rel',
    'P2': 'Temp',
    'P3': 'AF Corr',
    'P4': 'AF Learn',
    'P7': 'Boost abs',
    'P8': 'Rpm',
    'P9': 'KPH',
    'P10': 'Ign Time',
    'P11': 'Intake temp',
    'P12': 'MAF',
    'P13': 'Thrtl Angl',
    'P24': 'Atmo pres',
    'P25': 'Boost rel',
    'P29': 'Lrn Timing',
    'P30': 'Pedal Angl',
    'P36': 'WstGate Dty',
    'P90': 'IAM',
    'P91': 'FLKC'
}
